In [1]:
import numpy as np

precios = np.array(
    [24000, 28000, 22000, 30000, 8000])
con_iva = precios * 1.19

In [2]:
import numpy as np

precios = np.array([24000, 28000, 22000, 30000, 8000])
ceros = np.zeros(5) # [0. 0. 0. 0. 0.]
secuencia = np.arange(0, 10, 2) # [0 2 4 6 8]
rango = np.linspace(0, 1, 5) # [0. 0.25 0.5 0.75 1.]

matriz = np.array([[2, 24000],
[1, 28000],
[3, 22000]])

In [3]:
cantidades = np.array([2, 1, 3, 2, 1])
precios = np.array([24000, 28000, 22000, 30000, 8000])

ingresos = cantidades * precios # [48000 28000 66000 60000 8000]
con_descuento = precios * 0.9 # el escalar alcanza a los cinco
total = ingresos.sum() # 210000

In [4]:
precios = np.array([24000, 28000, 22000, 30000, 8000])

precios[0] # 24000 primer elemento
precios[-1] # 8000 último elemento
precios[1:4] # [28000 22000 30000] el final se excluye

mascara = precios > 20000 # [True True True True False]
precios[mascara] # [24000 28000 22000 30000]
precios[mascara].size # 4

np.where(precios > 25000, "alto", "normal")
# ['normal' 'alto' 'normal' 'alto' 'normal']

array(['normal', 'alto', 'normal', 'alto', 'normal'], dtype='<U6')

In [5]:
matriz = np.array([[48000, 28000],
[66000, 60000],
[ 8000, 12000]])

matriz.sum() # 222000
matriz.sum(axis=0) # [122000 100000]  #columnas
matriz.sum(axis=1) # [76000 126000 20000] #filas

array([ 76000, 126000,  20000])

In [6]:
import pandas as pd

serie = pd.Series([24000, 28000, 22000])
serie.to_numpy() # array([24000, 28000, 22000])

df = pd.DataFrame({
"producto": ["Bowl Andino", "Pasta Urbana"],
"precio": [24000, 28000],
})

type(df["precio"].to_numpy()) # <class 'numpy.ndarray'>

numpy.ndarray

In [7]:
##Fecha	Cliente ID	Producto	Categoría	Cantidad	Precio Unitario	Costo Unitario	Sede
##3/08/2026	101	Bowl Andino	Almuerzo	2	24.000,00	14.000,00	centro
##3/08/2026	102	Pasta Urbana	Almuerzo	1	28.000,00	17.000,00	NORTE
##4/08/2026	103	Bowl Andino	Almuerzo	1	24.000,00	14.000,00	Centro


datos_ventas = {"Fecha": ["3/08/2026", "3/08/2026", "4/08/2026"],
  "Cliente_ID": [101, 102, 103],
  "Producto": ["Bowl", "Pasta", "Bowl"],
  "Categoría": ["Almuerzo", "Almuerzo", "Almuerzo"],
"Cantidad": [2, 1, 1],
"Precio_Unitario": [24000, 28000, 24000],
"Costo_Unitario": [14.000, 17.000, 14.000],
"Sede": ["centro", "NORTE", "Centro"]}

print(datos_ventas)

{'Fecha': ['3/08/2026', '3/08/2026', '4/08/2026'], 'Cliente_ID': [101, 102, 103], 'Producto': ['Bowl', 'Pasta', 'Bowl'], 'Categoría': ['Almuerzo', 'Almuerzo', 'Almuerzo'], 'Cantidad': [2, 1, 1], 'Precio_Unitario': [24000, 28000, 24000], 'Costo_Unitario': [14.0, 17.0, 14.0], 'Sede': ['centro', 'NORTE', 'Centro']}

In [8]:
import pandas as pd

df_ventas = pd.DataFrame(datos_ventas)
type(df_ventas)

df_ventas.head()

,Fecha,Cliente_ID,Producto,Categoría,Cantidad,Precio_Unitario,Costo_Unitario,Sede
0,3/08/2026,101,Bowl,Almuerzo,2,24000,14.0,centro
1,3/08/2026,102,Pasta,Almuerzo,1,28000,17.0,NORTE
2,4/08/2026,103,Bowl,Almuerzo,1,24000,14.0,Centro

In [9]:
# una columna -> Series
df_ventas["Producto"]

# varias columnas -> DataFrame
columnas = ["Fecha", "Producto", "Cantidad", "Sede"]
df_ventas[columnas]

# columnas por posición
df_ventas.iloc[:, 0:3]

       Fecha  Cliente_ID Producto
0  3/08/2026         101     Bowl
1  3/08/2026         102    Pasta
2  4/08/2026         103     Bowl

In [10]:
mascara = (
(df_ventas["Sede"] == "Centro")
& (df_ventas["Categoría"] == "Almuerzo")
)

ventas_centro_almuerzo = df_ventas.loc[mascara, columnas].copy()

unidades_centro_almuerzo = ventas_centro_almuerzo["Cantidad"].sum()

In [11]:
df_ventas["ingreso"] = df_ventas["Cantidad"] * df_ventas["Precio_Unitario"]
df_ventas["costo_total"] = df_ventas["Cantidad"] * df_ventas["Costo_Unitario"]
df_ventas["margen_bruto"] = df_ventas["ingreso"] - df_ventas["costo_total"]
df_ventas["porcentaje_margen"] = (
df_ventas["margen_bruto"] / df_ventas["ingreso"] * 100

)

print(df_ventas)

       Fecha  Cliente_ID Producto Categoría  Cantidad  Precio_Unitario  \
0  3/08/2026         101     Bowl  Almuerzo         2            24000
1  3/08/2026         102    Pasta  Almuerzo         1            28000
2  4/08/2026         103     Bowl  Almuerzo         1            24000

   Costo_Unitario    Sede  ingreso  costo_total  margen_bruto  \
0            14.0  centro    48000         28.0       47972.0
1            17.0   NORTE    28000         17.0       27983.0
2            14.0  Centro    24000         14.0       23986.0

   porcentaje_margen
0          99.941667
1          99.939286
2          99.941667

In [12]:
kpi_producto = (
df_ventas
.groupby("Producto")
.agg(
unidades=("Cantidad", "sum"),
ingreso=("ingreso", "sum"),
margen=("margen_bruto", "sum"),
)
.reset_index()
)

kpi_producto["porcentaje_margen"] = (
kpi_producto["margen"] / kpi_producto["ingreso"] * 100
).round(2)

print(kpi_producto)

  Producto  unidades  ingreso   margen  porcentaje_margen
0     Bowl         3    72000  71958.0              99.94
1    Pasta         1    28000  27983.0              99.94

In [13]:
kpi_producto = kpi_producto.sort_values("ingreso", ascending=False)

producto_lider = kpi_producto.iloc[0]["Producto"] # Bowl Andino

# alternativa sin ordenar
indice = kpi_producto["ingreso"].idxmax()
producto_lider = kpi_producto.loc[indice, "Producto"]

print(producto_lider)

Bowl

In [15]:
def resumen_ejecutivo(df):
  ingreso = df["ingreso"].sum()
  margen = df["margen_bruto"].sum()

s1 = set(df.loc[df["semana"] == 1, "cliente_id"])
s2 = set(df.loc[df["semana"] == 2, "cliente_id"])
recurrentes = s1 & s2

return {
"total_ingresos": ingreso,
"margen_bruto": margen,
"porcentaje_margen": round(margen / ingreso * 100, 2),
"ticket_promedio": round(ingreso / len(df), 2),
"clientes_recurrentes": len(recurrentes),
"tasa_retencion": round(len(recurrentes) / len(s1) * 100, 2),
}

KeyError: 'semana'